### ISSUE TITLE
Add support for configuration of checkstyle pattern

### ISSUE THREAD

**Issue by deveth0** [pro-vision/jenkins-pv-pipeline-library#25]
Right now the pattern used to find checkstyle files is hardcoded in https://github.com/pro-vision/jenkins-pv-pipeline-library/blob/master/vars/defaultResultsStage.groovy

For Jacoco it's already possible to configure the pattern, this would be helpful for checkstlye too. 

Usecase: there are some maven/gradle plugins that support output in checkstyle format (e.g. ktlint) but they use different names / path for the results.

**Comment by tobias-richter** [comment]
@deveth0 sorry, but i am not able to put any effort into this issue right now. Feel free to create a PR with this improvement.
You are also able to customize the results stage using the _extend mechanism: https://github.com/pro-vision/jenkins-pv-pipeline-library/blob/master/vars/defaultResultsStage.md#_extend-optional

**Comment by deveth0** [comment]
Damn, thought so ;) gonna give it a try and see, if I can come up with a pr

**Comment by deveth0** [comment]
Thx for mergin
