### ISSUE TITLE
ERROR: No such library resource pv-pipeline-library/config/config.yaml could be found. Finished: FAILURE

### ISSUE THREAD

**Issue by deveth0** [pro-vision/jenkins-pv-pipeline-library#5]
Hi,

sorry, i'm not allowed to create branches here, but I think there is an error in the documentation:

[`step5`](https://github.com/pro-vision/jenkins-pv-pipeline-library/blob/master/docs/tutorials/setup-project-folder/README.md#step-5-ensure-that-the-library-is-working) of the tutorial describes how to test the pipeline. This fails as the provided script does not include the `jenkins-pipeline-configuration` that was setup in step 4. 

Imho the script should include all 3 libraries.

**Comment by tobias-richter** [comment]
@deveth0 The config.yaml step is part of [Step 1: Configure the pv-pipeline-library.](https://github.com/pro-vision/jenkins-pv-pipeline-library/blob/master/docs/tutorials/setup-project-folder/README.md#step-1-configure-the-pv-pipeline-library)

Please have a look at this step again. If you need further assistance please come back to us.

**Comment by deveth0** [comment]
yes. but in step 5 only the following libs are included:

    @Library ('pipeline-library') pipelineLibrary
    @Library ('pv-pipeline-library') pvPipelineLibrary

but the new library is missing afaics:
    
    @Library('pipeline-library-config') pipelineLibraryConfig

**Comment by tobias-richter** [comment]
@deveth0 Please look again at the screenshot! The "Load implicitly" checkbox is checked so the `pipeline-library-config` does not need a explicit loading.

**Comment by deveth0** [comment]
ahh sorry :) thx

**Comment by tobias-richter** [comment]
Added a red boarder in the image with https://github.com/pro-vision/jenkins-pv-pipeline-library/commit/214e4d9a1c2b05b31a6b7c5518ffe66cb492408b
