### ISSUE TITLE
Missing documentation for "defaultScmPoll" in config.yaml

### ISSUE THREAD

**Issue by deveth0** [pro-vision/jenkins-pv-pipeline-library#6]
The config.yaml contains a reference to defaultScmPoll but I could not find any documentation, how/where this property needs to be configured. 

The build fails with a lengthy stacktrace that defaultScmPoll could not be initialized. As soon as I configure the poll in my Jenkinsfile's config-map, I'm able to perform a build.

Could you please provide input, where the property needs to be configured? Thanks

**Comment by tobias-richter** [comment]
@deveth0 please see "https://github.com/pro-vision/jenkins-pv-pipeline-library/commit/2f7773abfd2d91794c637e094d13140d0b006cfe". `defaultScmPolling` is just a string in die context which is then used inside "`pollSCM(...)`"

**Comment by deveth0** [comment]
yeah, i know the format but i'd appreciate an example, in which file the defaultScmPolling needs to be configured. Or otherway round: shouldn't there be a sane default?

**Comment by tobias-richter** [comment]
@deveth0 i just updated the default value so now the configuration should be more easy to understand.

**Comment by deveth0** [comment]
nice, thx
